docs/consumers/loopback.rst

Using consumer.Loopback will cause in a type-error when starting gollum. Actual name of the consumer is consumer.LoopBack

Fixed lowercase b of LoopBack in the example

---

consumer/kinesis.go

Currently if `DefaultOffest` configuration is set to `newest` or `oldest`, and `OffsetFile` points to a file that does not contain all of the current kinesis shards then:
<pre>
iterator, err := cons.client.GetShardIterator(&iteratorConfig)
</pre>
will fail, with the following error:
<pre>
InvalidArgumentException: Must either specify (1) AT_SEQUENCE_NUMBER or AFTER_SEQUENCE_NUMBER and StartingSequenceNumber or (2) TRIM_HORIZON or LATEST and no StartingSequenceNumber. Request specified AFTER_SEQUENCE_NUMBER and no StartingSequenceNumber.
</pre>
With this patch the `DefaultOffset` will be respected on new shards, while shards found in the `OffsetFile` will use `ShardIteratorTypeAfterSequenceNumber`.

fix kinesis consumer to respect DefaultOffset

---

consumer/kinesis.go
producer/kinesis.go

currently the kinesis producer creates a kinesis record for each gollum message, and the consumer creates a gollum message for each kinesis record.
With this patch, the producer can optionally join multiple gollum messages into a single kinesis record, and the consumer can split kinesis records into multiple gollum messages.
Aggregating messages like this is desirable because records are rounded up to the next 25KB when determining cost and each shard in a stream is limited to 1K record/s or 1MB/s.

allow kinesis records to contain multiple messages

---

producer/kinesis.go

three issues from #22 
* documentation got out of sync with actual delimiter default
* accidentaly included some space indents instead of tab indents
* failed to properly estimate the length of `records.content.Records` the same as `records.original`

Fix three issues with #22

---

consumer/kinesis.go
core/consumer.go
core/producer.go
core/writerassembly.go
core/writerassembly_test.go
filter/rate.go
format/streamname.go
producer/elasticsearch.go
producer/kafka.go
shared/trie.go

The current goreportcard reports a few typos. See https://goreportcard.com/report/github.com/trivago/gollum#misspell
This PR fix this typos.

Fix typos found by goreportcard.com

---

Dockerfile

The Dockerfile is quite old. So it needs to get updated a bit.
This change includes the correct gollum path and introduced the filepermission change to be able to execute the gollum binary.

Fix Dockerfile to be able to build gollum image again.

---

.travis.yml
contrib/native/systemdconsumer.go
vendor/github.com/coreos/go-systemd/sdjournal/journal.go
vendor/github.com/coreos/pkg/dlopen/dlopen.go

Only builds with `-tags systemd`, and requires `cgo` and `systemd/sd-journal.h` to build successfully. Would've picked a pure-go reader for the systemd journal, but one doesn't seem to exist.

add systemd consumer

---

producer/elasticsearch.go

prevents panic in elasticsearch producer.
`atomic.AddInt64(prod.counters[index], 1)` only works if index hasn't had the date appended yet.

move DayBasedIndex handling to after counter

---

filter/any.go
filter/any_test.go

This filter allows multiple filters to be specified and accept if only one filter accepts. This is to allow behavior like rate limiting messages except if they start with `ERROR`, without rerouting messages that start with `ERROR`.

add filter.Any

---

consumer/kafka.go

Added some verbose information so that we can investigate reasons of the following exception. Probably it might happen when sarama suddenly close the channel so we get nil message from the channel.
```bash
goroutine 24 [running]:
panic(0xaa0620, 0xc420010040)
/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/trivago/gollum/consumer.(*Kafka).readFromPartition(0xc42015dc20, 0xc400000000)
/.../src/github.com/trivago/gollum/consumer/kafka.go:471 +0x240
created by github.com/trivago/gollum/consumer.(*Kafka).startReadTopic
/.../src/github.com/trivago/gollum/consumer/kafka.go:561 +0x183
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x48d3c0]
```

Added verbose info in order to investigate reasons of exception

---

format/templatejson.go
format/templatejson_test.go

This formatter parses a json message and passes it to text/template for formatting. It is intended for use with things like producer.S3's PathFormatter for more flexible naming

add format.TemplateJSON

---

format/processjson.go

without this format.ProcessJSON would fail to flatten keys containing json objects, because json objects must be cast to `map[string]interface{}` instead of `map[interface{}]interface{}`

Fix format.ProcessJSONs flatten directive

---

config/http_to_ws.conf
docs/producers/websocket.rst
producer/websocket.go

Run into an issue with the websocket server Origin default check. So added a flag to disable it. Also fixed an issue in case a connection upgrade fails.

websocket: Adding IgnoreOrigin and minor bug fix

---

consumer/kinesis.go
docs/consumers/kinesis.rst

Looking at the code, i think these args should be lowercase, right?
(also fixed a typo newset -> newest)

Updated aws kinesis config documentation

---

config/http_in_out.conf
producer/httprequest.go

- Accept full URLs for `prod.HTTPRequest`'s `Address` configuration parameter 
- Old "host:port" syntax still accepted
- Improve parsing of the parameter by delegating it to `net.URL`
- Fix https://github.com/trivago/gollum/issues/104 
- Fix parsing issues when using `RawData: true` mode
- Clarify documentation for the `Address` parameter

Bugfix/104: Improve parsing of Address parameter

---

producer/statsd.go

gauges have the convenient advantage over counters that they differentiate between no data and 0

add producer.Statsd support for sending a gauge

---

format/groktojson.go

Turns out the grok formatter can become quite verbose when handling lots of invalid data.
By setting the log level to "warning", we at least allow the user to set the log level to 0 and ignore the messages.

Decrease grok verbosity in case of parse errors

---

coordinator.go
core/logconsumer.go
router/distribute.go

The bug reported in issue #148 was caused by a log message being triggered by a log message in an infinite loop. To prevent this all log messages are now sent to a channel that is processed asynchronously in the event loop of core.logConsumer.  
This will slow down gollum at worst but it will not be stuck in an infinite loop anymore.
During shutdown (after the channel is closed) all messages will be forwarded to the logger.FallbackLogDevice so that no log messages get lost.

Fix for #148 blocking distribute

---

consumer/kinesis.go
producer/firehose.go
producer/kinesis.go
producer/s3.go

This change will allow gollum to be started like this:
```bash
AWS_DEFAULT_PROFILE=foobar gollum -c ...
```
This fixes #103 with a known way to change roles.

Fix for #103 Enabled shared config sessions for all AWS related plugins

---

coordinator.go
core/config.go
core/config_test.go
core/plugin.go
core/pluginconfig.go
core/pluginconfig_test.go
core/pluginconfigreader.go
core/pluginconfigreaderwitherror.go
core/pluginregistry.go
main.go
testing/configs/test_aggregated_pipeline.conf

Fix for #151, #172, fixing parts of #154
Configuration error handling and logging was broken in several ways.
The following fixes are included:
- config.Validate is now called again during startup (related to #154)
- "Streams" is now mandatory for consumers and producers
- "Stream" is now mandatory for routers
- fixed missing log messages during shutdown due to a missing purge
- fixed coloring of log messages during startup due to setting the formatter to late
- having no consumer/producers leads to shutdown
- proper use of logrus.WithError wthin main package

Fix for #151 config validation on startup

---

contrib/native/kafka/kafkaproducer.go
core/message.go
producer/kafka.go
router/metadata.go

Profiling showed that adding metadata to a message comes with some overhead.
As it is not needed in many cases, this PR makes it optional.
- Passing metadata to NewMessage will of course use that map directly (unless it is empty)
- GetMetadata creates the map if not existing
- TryGetMetadata returns nil (for read only access)
- FreezeOriginal will take into account that metadata can be nil
- Serialize and Deserialize already supported nil values

Make metadata an on-demand field

---

core/plugin.go
core/pluginregistry.go
core/pluginregistry_test.go
core/streamregistry.go
core/streamregistry_test.go

Some parts of the code neglected the fact that plugins are added during runtime.
The stream- and plugin-registry now use RWMutexes (as they act like caches) for improved read performance.

#195: race condition fix

---

docs/src/gen/formatter/metadatacopy.rst
docs/src/gen/formatter/runlength.rst
format/metadatacopy.go
format/metadatacopy_test.go
format/runlength.go

This change removes the sub formatters from metadata copy.
- It will simplify the formatter a lot
- There already is a possibility to change the created metadata fields later on
- The nested structure is bad to read and is counter intuitive because of non-processed fields
- It is somewhat duplicate code as the modulators have to be prepared
- It has additional runtime costs over the "top-level modulator" approach

Remove sub-formatters from MetadataCopy

---

producer/file.go
producer/file/targetFile.go

- fixed rotation issue if more than one stream write to the same target file 
```yaml
StdIn:
Type: consumer.Console
Streams: 
- foo
- bar
GollumOut:
Type: producer.File
Streams:
- foo
- bar
File: /tmp/gollum.log
Rotation:
Enable: true
SizeMB: 512
Prune:
Count: 7
```

fixed rotation issue if more than one stream write to the same target file

---

consumer/syslogd.go

This PR adds metadata support to the syslog consumer.
Also fixes a bug where the consumer would not try to remove an existing UDS file like consumer.Socket does.
```yaml
SyslogIn:
Type: consumer.Syslogd
Address: "udp://0.0.0.0:5150"
Format: "RFC3164"
SetMetadata: true
Streams: "syslog"
RouteByFacility:
Type: router.Metadata
Stream: "syslog"
Key: "facility"
Console:
Streams: "*"
Modulators:
- format.StreamName
- format.Envelope
```

Syslog metadata support

---

CHANGELOG.md
core/version.go
docs/src/gen/consumer/syslogd.rst
docs/src/gen/formatter/metadatacopy.rst
docs/src/gen/formatter/texttojson.rst
format/metadatacopy.go
format/metadatacopy_test.go
makefile

This extends the format.MetadataCopy filter to make it more useful.
The version shipped with 0.5.0 supported only metadata keys as targets.
The new version will allow copying payload / metadata from and to any destination inside the message. However, the support for multiple targets has been dropped as it can be achieved by adding multiple instances of the filter.
Append the value of a key to the payload
```yaml
format.MetadataCopy:
Key: foo
Mode: append
```
Copy the payload to a key (replace existing data)
```yaml
format.MetadataCopy:
ApplyTo: key
```

extend format.MetadataCopy to allow more precise copies

---

consumer/socket.go
testing/configs/test_socket.conf
testing/integration/aasocket_test.go
testing/integration/integration.go

Clean up the codebase for consumer.socket.
This also fixes a bug where gollum would hang during shutdown while trying to open a new connection. In addition to this a lot more debug output has been added and all errors are properly passed to logrus.
There are a few breaking changes on the configuration that require a mention:
* AckTimoutSec is now AckTimeoutSec
* ReadTimoutSec is now ReadTimeoutSec
* An empty value on Acknowledge does not force UDP anymore
* Using Acknowledge with UDP will cause an error
* Default protocol is now TCP (not affected by Acknowledge anymore)
```yaml
SocketUdp:
Type: consumer.Socket
Streams: data
Address: udp://127.0.0.1:5880
SocketTcp:
Type: consumer.Socket
Streams: data
Address: tcp://127.0.0.1:5881
SocketTcpAck:
Type: consumer.Socket
Streams: data
Address: …
```

Consumer.socket cleanup

---

docs/src/gen/consumer/socket.rst

The delimiter default is \n, but this renders as "n" in restructured text.
\\n produces an \n in the output

Doc fix: delimiter description is rendered incorrectly (n instead of \n)

---

consumer/kafka.go

In order to have consumer groups not start from the beginning if they all crash, and to be able monitor where they are; consumers need to commit their offsets. Technically consumer groups work without them, however it can lead to some unwanted behavior in failure scenarios.
```yaml
kafkaIn:
Type: consumer.Kafka
Streams: logs
Topic: logs
ClientId: "gollum log reader"
GroupId: "gollum"
Servers:
- "kafka0:9092"
- "kafka1:9092"
- "kafka2:9092"
- "kafka3:9092"
```

commit offsets to kafka when using consumer groups

---

format/metadatacopy.go
format/metadatacopy_test.go

Fixes of issue #229 
```yaml
default-input:
Streams:
- console
default-output:
Type: consumer.Console
Streams:
- console
Modulators:
- format.MetadataCopy:
ApplyTo: key
- format.SplitPick:
Index: 1
Delimiter: ':'
- format.MetadataCopy:
Key: key
Separator: '#'
Mode: prepend
- format.Envelope:
Postfix: "\n"
```

fixes #229: format.MetadataCopy integrity

---

.travis.yml
CHANGELOG.md
config/filescrape.conf
consumer/file.go
consumer/fileobservable.go
core/errors.go
core/errors_test.go
docs/src/gen/consumer/file.rst
testing/configs/test_aggregated_pipeline.conf
testing/configs/test_file_consumer.conf

Extend consumer.File to allow parsing multiple files at the same time by using glob patterns.
This introduces breaking changes.
```yaml
logFilesIn:
Type: consumer.File
Streams: logs
Files: "/var/log/*.log"
logFilesOut:
Streams: logs
```

Multi file scraping

---

CHANGELOG.md
consumer/syslogd.go

Referring to #234.
A non-standard protocol will be logged as "info" because it does not break anything.

Allow non-standard protocols for syslog consumer.

---

docs/src/instructions/bestPractice.rst
makefile

Make it easy to add the version of compiled in plugins to the gollum version string.
```
make build GOLLUM_RELEASE_SUFFIX=pkgVersionSuffix
./gollum -version
```

Enable plugin version injection in makefile

---

consumer/file.go
consumer/fileobservable.go

fix bug when using OffsetFilePath option for consumer.File
```yaml
"Fileinput":
Type: "consumer.File"
Files: /tmp/portal2Service.log
OffsetFilePath: "/tmp"
DefaultOffset: "oldest"
Delimiter: '^\d{4}-\d{2}-\d{2}T'
Streams:
- elastic
Modulators:
- format.GrokToJSON:
Patterns:
- '%{TIMESTAMP_ISO8601:timestamp} %{IP:client_ip}?\s*\[%{USERNAME:thread_id}\] %{DATA:uid} %{LOGLEVEL:log_level} \s*?%{USERNAME:service_name} -\s*(?s)%{GREEDYDATA:rest}'
"producer.Console":
Streams:
- "elastic"
Modulators:
- format.Envelope:
Prefix: "\n"
Postfix: "\n"
```
'make test' not running successfully on master branch of main repo

fixed error when using OffsetFilePath in consumer.File

---

consumer/file.go
docs/src/gen/consumer/file.rst
testing/configs/test_file_consumer_black.conf
testing/configs/test_file_consumer_blackwhite.conf
testing/configs/test_file_consumer_white.conf
testing/integration/fileConsumer_test.go
testing/integration/resultfile.go

This is an improvement over removing files from the streams after they have been scraped. For larger file scrapings (e.g. kubernetes logs) this will result in less overhead.
```yaml
logConsumer:
Type: consumer.File
Files: /var/log/*.log
BlackList: 'wifi.*'
WhiteList: 'wifi\..*'
Streams: out
out:
Streams: out
```
When used on a mac this will read all logs and the `wifi.log` file, but not files like `wifi-03-29-2019__10:58:44.764.log`. You can modify black and white list to achieve different results.

Add the possibility to filter file globs by regex.

---

core/message.go
core/message_test.go

- fixed cloning metadata
- fixed unit test for cloning metadata

Fix empty metadata after message cloning

---

consumer/socket.go

This fixes a bug in consumer.socket that may occur during shutdown.
The reason is that closeSocket() is called by the main thread as well as the listener thread and might cause cons.listener to be nil after passing the nil check.
This PR adds a mutex to solve that race condition

Fix socket.consumer closeSocket race condition

---

producer/socket.go
producer/spoolfile.go
producer/spooling.go

Since 0.5.0, the spooling format is broken, as messages are written to the spool file in plaintext and not as base64 encoded protobuf. 
```yaml
"Generator":
Type: "consumer.Profiler"
Streams: "profile"
Runs: 1000000
Batches: 1000
Characters: "abcdefghijklmnopqrstuvwxyz .,!;:-_"
Message: "%256s"
"SocketOut":
Type: "producer.Socket"
Streams: "profile"
ChannelTimeoutMs: 10
Address: "127.0.0.1:5880"
Modulators: 
- "format.Runlength"
ConnectionBufferSizeKB: 128
FallbackStream: "spooling"
Batch:
TimeoutSec: 1
Acknowledge: "OK"
"Spooler":
Type: "producer.Spooling"
Streams: "spooling"
Path: "test"
MaxFileSizeMB: 512```
```

Fix spoolfile message formatting

---

docs/src/instructions/bestPractice.rst

A directive is expecting flags following in the very next line. The body has to be separated with at least one empty line.

Fix ReStructuredText syntax in bestPractice.rst

---

Gopkg.lock
consumer/syslogd.go
testing/configs/test_syslog.conf

This fixes #253.
The default permissions are "0770" just like the socket consumer.
```yaml
SyslogdSocketConsumer:
Type: consumer.Syslogd
Streams: syslog
Address: "unix:///dev/log"
Format: "RFC3164"
Permissions: "0540"
"StdOut":
Type: "producer.Console"
Streams: syslog
```

Add permission support to syslog sockets
