Dockerfile
README.md

This PR adds a Dockerfile and the Documentation how to build/use gollum with docker.

Add Dockerfile and Documentation

---

contrib/rpm/gollum.service
contrib/rpm/gollum.spec
contrib/rpm/gollum.sysconfig

Add RPM spec file for building on RHEL7

---

consumer/kinesis.go

previously the kinesis consumer never actually wrote to `OffsetFile`, it would only read from it. with this patch, the kinesis consumer will write to `OffsetFile` every time it updates offsets.

write OffsetFile in kinesis consumer

---

producer/kinesis.go

currently `StreamMapping` requires that every stream be listed explicitly, or it will default to `streamName`
with this patch, `StreamMapping` will allow for a default stream other than `streamName` by specifying something like `StreamMapping: {"*": "default"}`
this matches the documentation at the bottom of: http://gollum.readthedocs.io/en/latest/producers/kinesis.html
the default config value was changed to ensure previous default bahavior.

kinesis producer allow * in StreamMapping

---

consumer/kafka.go
vendor/github.com/bsm/sarama-cluster/balancer.go
vendor/github.com/bsm/sarama-cluster/client.go
vendor/github.com/bsm/sarama-cluster/cluster.go
vendor/github.com/bsm/sarama-cluster/cmd/sarama-cluster-cli/main.go
vendor/github.com/bsm/sarama-cluster/config.go
vendor/github.com/bsm/sarama-cluster/consumer.go
vendor/github.com/bsm/sarama-cluster/doc.go
vendor/github.com/bsm/sarama-cluster/partitions.go

for #17
I need to test this more tomorrow.

add KafkaGroup consumer

---

format/processjson.go

also fixed a documentation comment saying misnaming the `time` directive as `timestamp`

add processjson directive to handle unix timestamps

---

format/processjson.go

so that `'Fields:flatten'` converts `{"Fields":{"message":"error"}}` to `{"Fields.message":"error"}`
and
so that `'messages:flatten:_'` converts `{"messages":["error1", "error2"]}` to `{"messages_0":"error1","messages_1:"error2"}`

add processjson directive to flatten values into new fields

---

filter/sample.go
filter/sample_test.go

This filter will accept `SampleRatePerGroup` out of every `SampleGroupSize` messages.

add sample filter

---

contrib/native/systemdconsumer.go

use journal.Wait() to notice journal rotations

---

producer/s3.go
producer/s3buffer.go

This ended up pretty much being a re-write of producer.S3, but I made sure it's backwards compatible and doesn't change output behavior unless new configuration options are used.

add file buffer and gzip to producer.S3

---

makefile

As the title says. Thanks for the fantastic project! 😃

append ".exe" to windows executable

---

consumer/http.go

This PR fixes #70 by making sure that we completely exhaust `req.Body`. 😃

fix incomplete read when using WithHeaders: false

---

core/message.go
core/message_test.go
core/messagehelper.go
core/messagehelper_test.go
filter/json.go
filter/regexp.go
format/metadatacopy.go
format/metadatacopy_test.go
producer/kafka.go
testing/configs/test_formatter.conf
testing/configs/test_regexp_filter.conf

Added MetaDataCopy formatter plugin

---

.travis.yml
consumer/profiler.go
contrib/native/kafka/kafkaproducer.go
core/message.go
core/pluginconfigreaderwitherror.go
format/metadatacopy_test.go
makefile
producer/kafka.go

This PR is related to issue #130:
- Added golint, gofmt, ineffassign to travis
- Optimised travis settings with matrix builds
- Added "fmt-check" to makefile
- Fixed linter issues
- Added ineffassign test to makefile
- Fixed ineffassign issues

Update travis settings

---

consumer/file.go

I'm using `consumer.File` and it's stat'ing a slow moving log file 1100-1800 times a second, which is causing performance issues.

add an option to slow down consumer.File's polling when reaching EOF

---

consumer/file.go

I'm supplying `consumer.File` with an absolute path, and it's stat'ing every directory in the path 1100-1800 times a second, which is causing performance issues.

add config to consumer.File to not resolve realFileName

---

core/logconsumer.go

Exchanged metric update function with rates

Log consumer metric rates

---

router/broadcast.go
router/distribute.go

* Fixed the routing order of router.Broadcast
* Improved the router.Distribute routing function (almost the same as router.Broadcast)

Routing order fix

---

Dockerfile-dev
contrib/native/kafka/kafkaproducer.go
contrib_loader.go.dist

* fixed breaking changes in native kafka producer
* provided new dockerfile-dev variant with installed pcap and kafka libs
_Note: only tested by compiling_

fix native kafka producer

---

producer/statsd.go

Integrated changes of #141 for 0.5.0

---

config/profile.conf
core/simplerouter.go
core/streamregistry.go
flags.go
glide.lock
main.go
signal_unix.go
signal_windows.go
testing/integration/main_test.go
vendor/github.com/davecgh/go-spew/LICENSE
vendor/github.com/davecgh/go-spew/spew/bypass.go
vendor/github.com/davecgh/go-spew/spew/dump.go
vendor/github.com/davecgh/go-spew/spew/format.go
vendor/github.com/golang/protobuf/jsonpb/jsonpb.go
vendor/github.com/golang/protobuf/proto/encode.go
vendor/github.com/golang/protobuf/proto/text_parser.go
vendor/github.com/pierrec/xxHash/xxHash32/xxHash32.go
vendor/github.com/pierrec/xxHash/xxHash64/xxHash64.go
vendor/github.com/sirupsen/logrus/exported.go
vendor/github.com/sirupsen/logrus/logger.go
vendor/github.com/sirupsen/logrus/text_formatter.go
vendor/github.com/trivago/tgo/tcontainer/bytepool.go
vendor/github.com/trivago/tgo/tnet/network.go
vendor/golang.org/x/crypto/ocsp/ocsp.go
vendor/gopkg.in/yaml.v2/decode.go
vendor/gopkg.in/yaml.v2/emitterc.go
vendor/gopkg.in/yaml.v2/yaml.go
vendor/gopkg.in/yaml.v2/yamlh.go

Based on #174 (please merge before this one) 
Fixes #154 and other minor issues
Gollum -tc not working was caused by a bug in the check for a missing config file.
Some minor cleanup and a regression fix for `gollum -v` is contained, too.

Fix for #154 test config

---

consumer/kinesis.go

As described in #132 this fixes the map access race condition when storing/reading offsets.
@mahdi-hdi Please check if this is working for you.

Fix for #132: Fix a race condition in consumer.Kinesis

---

README.md
docs/src/index.rst
docs/src/instructions/bestPractice.rst
docs/src/instructions/developing.rst
docs/src/instructions/index.rst
docs/src/instructions/installation.rst
docs/src/instructions/usage.rst
docs/src/plugins/index.rst
docs/src/releaseNotes/index.rst
docs/src/releaseNotes/v0.5.0.rst
makefile

* Reduced readme to a minimum
* Moved docs rst files
* Added new documentations

Docs updates

---

docs/src/gen/formatter/metadatacopy.rst
format/metadatacopy.go
format/metadatacopy_test.go
testing/configs/test_formatter.conf

Changed settings of format.MetadataCopy from array to map

Changed settings of format.MetadataCopy from array to map

---

consumer/consumers_test.go
core/simpleconsumer.go
core/simpleproducer.go
docs/src/instructions/healthchecks.rst
docs/src/instructions/index.rst

* fixed missing health check in simple consumer
* added health check docs
```yaml
Profiler:
Type: aggregate
Runs: 100000
Batches: 100
Characters: "abcdefghijklmnopqrstuvwxyz .,!;:-_"
Message: "%256s"
Streams: "profile"
KeepRunning: true
ModulatorRoutines: 0
Aggregate:
C1:
Type: consumer.Profiler
C2:
Type: consumer.Profiler
C3:
Type: consumer.Profiler
Benchmark:
Type: "producer.Benchmark"
Streams: "profile"
```

fixed missing health check implementation in simple consumer

---

core/errors_test.go
core/filterresult_test.go
core/modulator_test.go
format/collectd_test.go

- Add missing unit tests
_no config_

Increase code coverage

---

core/pluginconfigreaderwitherror.go

Fixed issue in `GetPluginArray()` method that the type casting was too strict
```yaml
StdIn:
Type: "consumer.Console"
Streams: StreamIn
Modulators:
- format.MetadataCopy:
WriteTo:
hostname:
- format.Hostname
foo:
- format.Base64Encode:
Dictionary:  "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"
bar: []
```

made GetPluginArray() more flexible

---

main.go
makefile

Increase visibility by bumping the version after rebuilding Gollum against the latest protobuf definitions. The imports were moved automatically by gofmt.

Bump dev branch to v0.4.6.3

---

config/spooling.conf
core/pluginconfigreader.go
core/router.go
core/streamregistry.go

This PR fixes bug #213 
You can use the config/spooler.conf

Fix core.Router struct tag assignment

---

producer/elasticsearch.go

Computer programs don't have issues, they encounter errors

 s/Issue/Error/ in error messages

---

.travis.yml
consumer/awsKinesis.go
consumer/http.go
contrib/deprecated/producer/s3buffer.go
core/components/awsMultiClient.go
core/components/batchedWriterAssembly.go
core/config.go
core/plugin.go
filter/json.go
format/aggregate.go
format/extractjson.go
format/formatters_test.go
format/groktojson.go
format/jsontoarray.go
format/jsontoinflux10.go
main.go
makefile
producer/InfluxDBWriter08.go
producer/InfluxDBWriter09.go
producer/InfluxDBWriter10.go
producer/awss3/byteBuffer.go
producer/file/targetFile.go
producer/kafka.go
producer/redis.go
producer/scribe.go
producer/websocket.go
testing/integration/gollumhandle.go
testing/integration/resultfile.go
testing/integration/startindicator.go

maintenance PR to add go 1.12 and fix recent linter warnings in daily builds

Support go 1.12 in travis builds
